apiVersion: v1
kind: Pod
metadata:
  name: example-webserver
  namespace: team1
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80

