apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team2-ingress
  namespace: ingress-team2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: team2-ingress
  rules:
  - host: team2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: team2-service
            port:
              number: 80
  tls:
  - hosts:
    - team2.example.com
    secretName: team2-tls
