apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy-ingress
  source:
    repoURL: https://haproxytech.github.io/helm-charts
    chart: kubernetes-ingress
    targetRevision: 1.36.0
    helm:
      values: |
        service:
          type: LoadBalancer 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
