controller:
  kind: Deployment
  service:
    type: LoadBalancer
  extraArgs: "-configmap=ingress-ha/sni-routing-config"
  tcp:
    "443": "team1.example.com:443,team2.example.com:443,team3.example.com:443,team4.example.com:443"
  ingressClassResource:
    enabled: false
  logging:
    level: debug
